### ISSUE TITLE
ObjectPreview should be used in place of ObjectLabel

### ISSUE THREAD

**Issue by jcready** [storybookjs/react-inspector#95]
Collapsed nested objects/arrays in Chrome's devtools show the preview of the value not just `Object` or `Array`, upon expansion the preview goes away for objects, but not for arrays. 

![react-inspector](https://user-images.githubusercontent.com/358876/66863604-63fe7f00-ef61-11e9-94b9-4dd4b3e7696c.gif)

The preview also prevents line-wrapping using the following CSS:

```css
TreeNode {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```

I would love to be able to customize these things to suit my needs, but none of these things are configurable do to the way things are encapsulated. So for now this is simply a bug.
